"""create temperatures table

Revision ID: 88884a7250e7
Revises: fc2d93ed75fe
Create Date: 2026-01-06 13:18:50.944166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88884a7250e7"
down_revision: Union[str, Sequence[str], None] = "fc2d93ed75fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temperatures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("date_time", sa.DateTime(timezone=True),
                  index=True,
                  nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_temperatures_city_id"), "temperatures", ["city_id"], unique=False
    )
    op.create_index(
        op.f("ix_temperatures_date_time"), "temperatures", ["date_time"], unique=False
    )
    op.create_index(op.f("ix_temperatures_id"), "temperatures", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_temperatures_id"), table_name="temperatures")
    op.drop_index(op.f("ix_temperatures_date_time"), table_name="temperatures")
    op.drop_index(op.f("ix_temperatures_city_id"), table_name="temperatures")
    op.drop_table("temperatures")
    # ### end Alembic commands ###
